---
- name: Ensure firewalld is running and enabled on boot
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Accept mysql port
  firewalld:
    service: mysql
    permanent: true
    state: enabled
  notify: restart firewalld
