---
- name: create symbolic link to _vimrc
  file: src=~/dotfiles/_vimrc dest=~/.vimrc state=link

- name: create bundle directory
  file: path=~/.vim/bundle state=directory

- name: create symbolic link to neobundle
  file: src=~/dotfiles/.vim/bundle/neobundle.vim dest=~/.vim/bundle/neobundle.vim state=link
