---
- name: Ensure firewalld is running and enabled on boot
  become: yes
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Set fluentd port
  become: yes
  template:
    src: fluentd_firewalld.xml.j2
    dest: /etc/firewalld/zones/fluentd.xml
  notify: restart firewalld

- name: Set default public port
  become: yes
  template:
    src: public_firewalld.xml.j2
    dest: /etc/firewalld/zones/public.xml
  notify: restart firewalld
