---
- name: update yum
  become: yes
  yum: name=* state=latest

- include: gcc.yml
- include: git.yml
- include: ruby.yml
- include: gem.yml
- include: nginx.yml
- { include: mysql.yml, become: yes }
- { include: firewalld.yml, become: yes }
