---
- name: Include OS-specific variables.
  include_vars: RedHat-7.yml

- name: Define mysql_packages
  set_fact:
    mysql_packages: "{{__mysql_packages | list}}"
  when: mysql_packages is not defined

- name: Define mysql_daemon.
  set_fact:
    mysql_daemon: "{{__mysql_daemon | list}}"
  when: mysql_daemon is not defined

- name: Define mysql_slow_query_log_file.
  set_fact:
    mysql_slow_query_log_file: "{{__mysql_slow_query_log_file | list }}"
  when: mysql_slow_query_log_file is not defined

- include: mysql-setup-RedHat.yml

- name: Check if MySQL packages were installed.
  set_fact:
    mysql_install_packages: "{{ (rh_mysql_install_packages is defined and rh_mysql_install_packages.changed) or (deb_mysql_install_packages is defined and deb_mysql_install_packages.changed) }}"

- include: mysql-configure.yml
- include: mysql-secure-installation.yml
- include: mysql-databases.yml
- include: mysql-users.yml
- include: mysql-replication.yml
