eap_home: /opt/jboss-eap-6.4
ews_home: /opt/jboss-ews-2.1

#######################
# app_websettings
# admin_firewalld.xml.j2
#######################
admin_firewalld_allow_ips:
  - { ip: "10.0.2.2" }

#######################
# app_websettings
# general_firewalld.xml.j2
#######################
general_firewalld_allow_ips:
  - { ip: "192.168.33.0/24" }

#######################
# fluentd
# fluentd_firewalld.xml.j2
#######################
fluentd_firewalld_allow_ips:
  - { ip: "192.168.33.0/24" }

#######################
# eap
# ews
# td-agent.conf.xml.j2
#######################
td_agent_logserver_ip: "192.168.33.13"
