---
- name: Ensure firewalld is running and enabled on boot
  become: yes
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Set port for public
  become: yes
  template:
    src: general_firewalld.xml.j2
    dest: /etc/firewalld/zones/general.xml
  notify: restart firewalld

- name: Set port for administration
  become: yes
  template:
    src: admin_firewalld.xml.j2
    dest: /etc/firewalld/zones/admin.xml
  notify: restart firewalld

- name: Set default public port
  become: yes
  template:
    src: public_firewalld.xml.j2
    dest: /etc/firewalld/zones/public.xml
  notify: restart firewalld
