# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ba5e6edba160df010536d468cd4d2bf7814f454bec17fbf154ccd4a9abb65fc6640494c53a824e6ab0745d6f489fc67c28d4ed4816b90d46844c21c9cbb13bd

test:
  secret_key_base: 8ef49e39c537da5cc0470b08fd6f8d63764fc7cb64f3d6ec3ceeb19794d3c6e018936794a8bae48168ead5bd8565a036ee2275559afcce0e849a6248e8158cd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
