---
- name: create bash_profile if not exist
  file: path=~/.bash_profile state=touch

- name: set ls color
  lineinfile:
    dest: ~/.bash_profile
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: "^alias ls='ls -G'"
      line: "alias ls='ls -G'"
    - regexp: "^export LSCOLORS=gxfxcxdxbxegedabagacad"
      line: "export LSCOLORS=gxfxcxdxbxegedabagacad"
