---
- name: set ls color
  blockinfile:
    dest: ~/.bash_profile
    block: |
      alias ls='ls -G'
      export LSCOLORS=gxfxcxdxbxegedabagacad
#
# - name: update yum
#   become: yes
#   yum: name=* state=latest
#
# - name: install latest git module
#   become: yes
#   yum: name=git state=latest
